name : auto-test

on :
  schedule :
#   매일 00시에 테스트가 실행됨
    [ cron : "0 15 * * *" ]
  push :
    branches :
      [ master ]

jobs :
  test :
    runs-on :
      ubuntu-latest
    
    steps :
     - uses : actions/checkout@v3
     - name : Set up JDK 17
       uses : actions/setup-java@main
       with :
          java-version: '17'
          distribution: 'adopt'
          
     - name : Change Permission
       run : chmod +x ./gradlew
    
     - name : Test with Gradle
       run : ./gradlew clean test
