name : auto-test

on :
  schedule :
#   매일 00시에 테스트가 실행됨
    [ cron : "0 15 * * *" ]
  push :
    branches :
      [ master ]

jobs :
  test :
    runs-on :
      ubuntu-latest
    
    steps :
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'community'
          mysql user: 'seongmin'
          mysql password: ${{ secrets.MySQL_PASSWORD }} # github Secret 탭에서 설정하세요!
          
      - uses : actions/checkout@v3
      - name : Set up JDK 17
        uses : actions/setup-java@main
        with :
            java-version: '17'
            distribution: 'adopt'
          
      - name : Change Permission
        run : chmod +x ./gradlew
    
      - name : Test with Gradle
        run : ./gradlew clean test
